### ISSUE TITLE
[FacebookRequestError] (#2663) Terms of service has not been accepted.

### ISSUE THREAD

**Issue by froghramar** [facebook/facebook-nodejs-ads-sdk#26]
I ran the sample code from the docs of facebook marketing api. And I am continuously getting this error.

> {"name":"FacebookRequestError","message":"(#2663) Terms of service has not been accepted. To accept, go to https://www.facebook.com/customaudiences/app/tos/?act=xxxxxxxxx","stack":"Error\n    at FacebookRequestError.FacebookError [as constructor] (/app/node_modules/facebook-nodejs-ads-sdk/dist/cjs.js:319:16)\n    at new FacebookRequestError (/app/node_modules/facebook-nodejs-ads-sdk/dist/cjs.js:341:129)\n    at /app/node_modules/facebook-nodejs-ads-sdk/dist/cjs.js:507:15\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)","status":400,"response":{"error":{"message":"(#2663) Terms of service has not been accepted. To accept, go to https://www.facebook.com/customaudiences/app/tos/?act=xxxxxxxx","type":"OAuthException","code":2663,"fbtrace_id":"xxxxxx"}},"method":"POST","url":"https://graph.facebook.com/v2.11/act_xxxxxxx/customaudiences?access_token=xxxxxx","data":{"name":"Past 30 days","pixel_id":"xxxxxx","prefill":true,"rule":{"url":{"i_contains":""}},"subtype":"WEBSITE","retention_days":"30","id":"act_xxxxxxxx"}}

The error provides a link which is invalid (facebook says). May be this error is not related with the implementation of this package. But is there anyone who knows the reason for this error.

**Comment by froghramar** [comment]
I find out that this error is not related with the implementation of this package.
