### ISSUE TITLE
Intermittent problem when calling account.createCampaign

### ISSUE THREAD

**Issue by roundrobin** [facebook/facebook-nodejs-ads-sdk#5]
While 3/4 calls work, every other call I'm getting the following error message when calling `account.createCampaign`:

```
{ message: 'Unsupported post request. Object with ID \'SOME_CAMPAIGN_ID\' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api',
        type: 'GraphMethodException',
        code: 100,
        error_subcode: 33,
        fbtrace_id: 'DV8Huvneiyi' }
```

is it possible something is being cached in the background from a previous call?

Best roundrobin

For context: I'm calling the method from within a Express endpoint.

**Comment by zanyaziz** [comment]
Could you forward me the exact code that you are using? I'd like to debug through it since I am not able to reproduce the issue.

**Comment by roundrobin** [comment]
```
 account
        .createCampaign([], {
            [Campaign.Fields.name]: "Campaign name",
            [Campaign.Fields.status]: Campaign.Status.paused,
            [Campaign.Fields.objective]: "LINK_CLICKS",
            [Campaign.Fields.spend_cap]: 12000
        })
        .then(campaign => {
            console.log("integration:facebook:createdCampaign", campaign);
        });

```

**Comment by roundrobin** [comment]
What surprises me is that the error message knows about a campaign id (`SOME_CAMPAIGN_ID `) even though at this point the campaign creation didn't go through.

**Comment by roundrobin** [comment]
Not sure if this helps, but here is a stack trace that is printed in the terminal.

```
    at FacebookRequestError.FacebookError [as constructor] (/Code/node_modules/facebook-nodejs-ads-sdk/dist/cjs.js:314:16)
    at new FacebookRequestError (/Code/node_modules/facebook-nodejs-ads-sdk/dist/cjs.js:337:129)
    at /Code/node_modules/facebook-nodejs-ads-sdk/dist/cjs.js:456:15
    at tryCatcher (/Code/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Code/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Code/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Code/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Code/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Code/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Code/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Code/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by roundrobin** [comment]
@zanyaziz Let me know, I can also provide a lightweight example within a express.js app.

**Comment by Ivkaa** [comment]
@roundrobin I had same issue, fixed it by appending 'act_' to <AD_ACCOUNT_ID> like this
```
new AdAccount('act_' + config.fb.marketingAdId)
```

**Comment by Ivkaa** [comment]
@roundrobin Hey, I've got bug that acts same as you described, even the stacktrace is same. It happens when I make subsequent requests and it's because the AdAccountId is different (not the one I entered as argument when creating AdAccount). 

```
{ error:
      { message: 'Unsupported post request. Object with ID \'12033000xxx\' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api',
        type: 'GraphMethodException',
        code: 100,
        error_subcode: 33,
        fbtrace_id: 'AXwvThfAkIs' } },
  method: 'POST',
  url: 'https://graph.facebook.com/v2.10/1203300xxx/ads?access_token=xxx',
```

**Comment by Ivkaa** [comment]
@zanyaziz Okay, so here you have a snippet that shows how i made it work again:

```
const { FacebookAdsApi, AdAccount, Ad, AdCreative } = require('facebook-nodejs-ads-sdk')
const config = require('../config')

const fbAdsApi = FacebookAdsApi.init(config.fb.marketingApiKey)

if (process.env.NODE_ENV !== 'production') {
  fbAdsApi.setDebug(true)
}

const fbAccount = new AdAccount('act_' + config.fb.marketingAdId)

module.exports.createAd = async function createAd(survey) {
  const adCreativeResponse = await fbAccount.createAdCreative(
    [],
    {
      [AdCreative.Fields.name]: survey.title,
      [AdCreative.Fields.title]: survey.title,
      [AdCreative.Fields.body]: survey.description,
      [AdCreative.Fields.link_url]: 'https://google.com,
      [AdCreative.Fields.object_url]: 'https://google.com',
      [AdCreative.Fields.image_url]: survey.photo.url
    }
  )

  **fbAccount._data.id = 'act_' + config.fb.marketingAdId** // HERE: this is how I set the right id and this solves the issue, I think this can help you find where the problem is

// This second part throws error, but completely different and related to fields
  const adResponse = await fbAccount.createAd(
    [],
    {
      [Ad.Fields.name]: `Survey with title: ${survey.title}`,
      [Ad.Fields.creative]: { creative_id: adCreativeResponse.id },
      [Ad.Fields.status]: Ad.Status.paused
    }
  )

  return adResponse
}
```
